FROM neo4j:3.4.4
MAINTAINER Duy Anh <duyanhnguyenngoc97@gmail.com>

ADD init.sh /init.sh
ADD ./dump /

#WORKDIR /

#RUN \
# chmod +x /init.sh && \
#  && \
#  && \
#  && \

#ENTRYPOINT ["/init.sh"]

EXPOSE 7474 7473 7687