version: "3"
services:

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootmysql
      MYSQL_USER: cinnamon_flax
      MYSQL_PASSWORD: cinnamon_flax
      MYSQL_DATABASE: cinnamon_flax
    volumes:
      - db_data:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      cinnamon_flax:
        ipv4_address: 172.28.0.3

  redis:
    image: redis
    ports: 
      - "6379:6379"
    networks:
      cinnamon_flax:
        ipv4_address: 172.28.0.2

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      WORKDIR: /code
      MYSQL_USER: cinnamon_flax
      MYSQL_PASSWORD: cinnamon_flax
      MYSQL_DATABASE: cinnamon_flax
      MYSQL_HOST: mysql_host
      CELERY_BROKER_URL: redis://172.28.0.2/1
      CELERY_RESULT_BACKEND: redis://172.28.0.2/1
    volumes:
      - ./:/code
      - /data:/data
      - /debug:/debug
      - /var/log:/var/log
      - /var/run:/var/run
    networks:
      cinnamon_flax:
        ipv4_address: 172.28.0.4
    command: /bin/bash /code/entrypoint.sh

volumes:
  db_data:
    external: false

networks:
  cinnamon_flax:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
