version: "3"

networks:
  ctcnet:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.97.97.0/24
#        gateway: 172.97.97.1

volumes:
  db_data:
    external: false

services:

  postgres_database:
    container_name: postgres_database_esabatad_sergtsop_1
    build: ./postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
    - ./postgres/data:/var/lib/postgresql/data
    restart: always
    ports:
    - 5432:5432
    networks:
      ctcnet:
        ipv4_address: 172.97.97.2

  cinamon_mysql:
    container_name: cinamon_mysql_lqsym_nomanic_1
    image: mysql:5.7
    restart: always
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootmysql
      MYSQL_USER: cinnamon_flax
      MYSQL_PASSWORD: cinnamon_flax
      MYSQL_DATABASE: cinnamon_flax
    volumes:
    - db_data:/var/lib/mysql
    - ./cinamon-api/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      ctcnet:
        ipv4_address: 172.97.97.3

  cinamon_redis:
    container_name: cinamon_redis_sider_nomanic_1
    image: redis
    restart: always
    ports:
    - 6379:6379
    networks:
      ctcnet:
        ipv4_address: 172.97.97.4

  cinamon_app:
    container_name: cinamon_app_ppa_nomanic_1
    build: ./cinamon-api
    restart: always
    ports:
    - 8000:8000
    depends_on:
    - cinamon_mysql
    - cinamon_redis
    environment:
      WORKDIR: /code
      MYSQL_USER: cinnamon_flax
      MYSQL_PASSWORD: cinnamon_flax
      MYSQL_DATABASE: cinnamon_flax
      MYSQL_HOST: mysql_host
      CELERY_BROKER_URL: redis://172.97.97.4/1
      CELERY_RESULT_BACKEND: redis://172.97.97.4/1
    volumes:
    - ./cinamon-api:/code
    - /data:/data
    - /debug:/debug
    - /var/log:/var/log
    - /var/run:/var/run
    networks:
      ctcnet:
        ipv4_address: 172.97.97.5
    command: /bin/bash /code/entrypoint.sh

  ctc_webapp:
    container_name: ctc_webapp_ppabew_ctc_1
    build: ./
    restart: always
    ports:
    - 8088:8088
    environment:
      DNS_POSTGRES: 172.97.97.2
      DNS_OCR_API_SERVER: 172.97.97.5
    volumes:
    - ./src/main/resources/static/files:/app/src/main/resources/static/files
    depends_on:
    - postgres_database
    - cinamon_app
    networks:
      ctcnet:
        ipv4_address: 172.97.97.6


