FROM microsoft/mssql-server-linux:2017-latest
MAINTAINER Duy Anh <duyanhnguyenngoc97@gmail.com>

ADD init.sh /init.sh
ADD ./restore /

#WORKDIR /

#RUN \
# chmod +x /init.sh && \
#  && \
#  && \
#  && \

#ENTRYPOINT ["/init.sh"]

EXPOSE 1433