version: "3"

networks:
  ctcnet:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.97.97.0/24
#        gateway: 172.97.97.1

services:

  postgres_database:
    container_name: postgres_database_esabatad_sergtsop_1
    build: ./
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
    - ./data:/var/lib/postgresql/data
    restart: always
    ports:
    - 5432:5432
    networks:
      ctcnet:
        ipv4_address: 172.97.97.2
